#!/bin/bash
# Mon Feb 21 11:17:13 PST 2011 <troydwill@gmail.com>
source ./rrp-lib.sh
rails generate controller welcome index login logout
${EDITOR} ${TOP_DIR}/config/routes.rb
mv -iv ${TOP_DIR}/public/index.html /tmp/
