#!/bin/bash
source ./rrp-lib.sh
NAME='setting' # lower case singular

function do_generate () {
    rails generate scaffold ${NAME} \
	user_id:integer \
	start_weight:decimal \
	start_time:datetime \
	weight_loss_rate:integer
}

function edit_model () {
    MODEL="${TOP_DIR}/app/models/${NAME}.rb"
    cat >> ${MODEL} <<EOF
  belongs_to :user
  validates :user_id, :presence => true, :numericality => true
  validates :weight_loss_rate, :numericality => true
EOF

    $EDITOR ${MODEL}

    echo "Don't forget to edit foreign key model, if applicable" && sleep 1
    
}

function do_migration () {
    read -p "Run db:migrate? <Ctrl-C> to quit" && rake db:migrate
}

###### Main program #######

do_generate
edit_model
do_migration
