#!/bin/bash
source ./lib-rrp
NAME='reading' # lower case singular

function do_generate () {
    rails generate scaffold ${NAME} \
	user_id:integer \
	weight:decimal \
	reading_time:datetime
}

function edit_model () {
    MODEL="${TOP_DIR}/app/models/${NAME}.rb"
    cat >> ${MODEL} <<EOF
  belongs_to: user
  validates :user_id, :numericality => true
  validates :weight, :numericality => true
EOF

    $EDITOR ${MODEL}

    echo "Don't forget to edit foreign key model, if applicable" && sleep 1
    
}

function do_migration () {
    read -p "Run db:migrate? <Ctrl-C> to quit" && rake db:migrate
}

###### Main program #######

do_generate
edit_model
do_migration
