#!/bin/bash
set -o errexit
source ./lib-rrp

NAME='user'

function up () {
    rails generate scaffold ${NAME} \
	name:string \
	email:string \
	phone:string \
	height:decimal \
	sex:string \
	goal_start_weight:decimal \
	goal_start_time:datetime \
	goal_loss_rate:integer \
	filter_rate_gain:integer \
	filter_rate_loss:integer \
	shared_doc:string
}

function down () {
    echo
}

function edit_model () {
    cat >> ${TOP_DIR}/app/models/${NAME}.rb <<EOF
  validates :name, :presence => true
  validates :email, :presence => true, :uniqueness => true
  validates :phone, :presence => true
  validates :height, :presence => true, :numericality => true
  validates :sex, :presence => true
  validates :goal_start_weight, :presence => true, :numericality => true
  validates :goal_start_time, :presence => true, :numericality => true
  validates :goal_loss_rate, :presence => true, :numericality => true
  validates :filter_rate_gain, :presence => true, :numericality => true
  validates :filter_rate_loss, :presence => true, :numericality => true
  validates :shared_doc, :presence => true
EOF
    $EDITOR ${TOP_DIR}/app/models/${NAME}.rb
}

up
edit_model
echo "If ready do 'rake db:migrate' to update database"
