#!/bin/bash
set -o errexit
source ./lib-rrp
LOGIN_PAGE="${TOP_DIR}/app/views/welcome/login.html.erb"

function edit_login_form () {

cat >> ${LOGIN_PAGE} <<EOF
<fieldset>
  <legend>Please Log In</legend>
  <% form_tag do %>
    <p>
      <label for="email">Email:</label>
      <%= text_field_tag :email, params[:email] %>
    </p>
    <p>
      <%= submit_tag "Login" %>
    </p>
  <% end %>
</fieldset>
EOF

${EDITOR} ${LOGIN_PAGE}

}

edit_login_form

${EDITOR} ${TOP_DIR}/config/routes.rb
