#!/bin/bash
set -o errexit
source ./lib-rrp

USER_MODEL="${TOP_DIR}/app/models/user.rb"

function add_authenticate_method () {

    cat >> ${USER_MODEL} <<EOF
# Agile book uses more elaborate method with more security
# def self.authenticate(username, password)
def self.authenticate(email)
#  user = self.find_by_username(username)
  user = self.find_by_email(email)
  if user
#    if user.password != password
    if user.email != email
      user = nil
    end
  end
  user
end
EOF

    ${EDITOR} ${USER_MODEL}

}

add_authenticate_method
